title: Adventa Makina
description: "Adventa delivers professional flatbed CNC router solutions engineered for furniture makers, interior builders, and manufacturers."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adventacnc.com.tr" # the base hostname & protocol for your site
